# Generated by Django 4.0.4 on 2022-05-28 05:35

import app.models.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'facilities'},
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(max_length=17, validators=[app.models.validators.validate_VIN]),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('name', 'address')},
        ),
        migrations.CreateModel(
            name='LoadHistoryEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2022, 5, 28, 5, 35, 45, 174026))),
                ('text', models.CharField(max_length=200)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.load')),
            ],
        ),
    ]
