# Generated by Django 4.0.4 on 2022-05-31 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadhistoryevent',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 8, 48, 33, 288339)),
        ),
    ]
