# Generated by Django 4.0.4 on 2022-06-05 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_driver_username_alter_loadhistoryevent_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='username',
        ),
        migrations.AddField(
            model_name='driver',
            name='chat_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadhistoryevent',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 19, 56, 49, 994393)),
        ),
    ]
