# Generated by Django 4.0.4 on 2022-05-28 05:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_address_options_alter_facility_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadhistoryevent',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 5, 36, 24, 505534, tzinfo=utc)),
        ),
    ]
