# Generated by Django 4.0.4 on 2022-05-28 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_loadhistoryevent_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadhistoryevent',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 5, 36, 59, 115272)),
        ),
    ]
