# Generated by Django 4.0.4 on 2022-05-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='note',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
