# Generated by Django 4.0.4 on 2022-05-28 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_loadhistoryevent_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='status',
            field=models.CharField(choices=[('Set up', 'Set up'), ('Available', 'Available'), ('Pending', 'Pending'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Invoiced', 'Invoiced')], max_length=11),
        ),
        migrations.AlterField(
            model_name='loadhistoryevent',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 11, 16, 45, 591469)),
        ),
    ]
