# Generated by Django 4.0.4 on 2022-05-26 08:25

import app.models.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_facility_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50)),
                ('rate', models.PositiveSmallIntegerField()),
                ('empty_miles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('loaded_miles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('group', models.CharField(choices=[], max_length=5)),
                ('TONU', models.BooleanField(default=False)),
                ('notes', models.TextField(max_length=100)),
                ('broker_company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.brokercompany')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='coordinator', to='app.profile', validators=[app.models.validators.validate_coordinator])),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.driver', validators=[app.models.validators.driver_for_load_validator])),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entered_by', to='app.profile')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.trailer')),
            ],
        ),
        migrations.CreateModel(
            name='Accessorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('DETENTION', 'Detention'), ('LAYOVER', 'Layover'), ('EXTRA MILES', 'Extra miles')], max_length=11)),
                ('amount', models.PositiveSmallIntegerField()),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.load')),
            ],
        ),
        migrations.CreateModel(
            name='LoadUnloadStage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.BooleanField(default=True)),
                ('order_number', models.PositiveSmallIntegerField()),
                ('time_from', models.DateTimeField()),
                ('time_to', models.DateTimeField()),
                ('actual_time_from', models.DateTimeField(blank=True, null=True)),
                ('actual_time_to', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(max_length=50)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.facility')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.load')),
            ],
            options={
                'unique_together': {('load', 'order_number')},
            },
        ),
    ]
