# Generated by Django 4.0.4 on 2022-05-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_load_accessorial_loadunloadstage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='load',
            name='group',
            field=models.CharField(choices=[('PP', 'Priority pool'), ('PPL', 'Priority pool loaded'), ('URGENT', 'Urgent')], max_length=6),
        ),
    ]
