# Generated by Django 4.0.4 on 2022-05-26 11:46

import app.models.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_active_driver_is_active_alter_load_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loadunloadstage',
            unique_together={('load', 'order_number', 'type')},
        ),
        migrations.AddField(
            model_name='load',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Invoiced', 'Invoiced')], default='Available', max_length=11),
        ),
        migrations.AlterField(
            model_name='load',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.driver', validators=[app.models.validators.driver_for_load_validator]),
        ),
        migrations.AlterField(
            model_name='load',
            name='notes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loadunloadstage',
            name='note',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
